language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: heroku
  api_key:
   secure: "TvCja19P8meXAqcd0PKyF2F0zzMBASN0ej8KRgjDcdjjqOSQSG4j3asbPGYTfYqWBf6lbLpdRtQS2J2WMoiDRaGYwzK1MU29iuPM9QS9K3UPb7583Hdx79Im5qoHrPk0Q3V7CtHinmTPXZ5zizbowWVBWuC/OfZqBHi7cOjIG3iPhQJjh5K+YtuQYSIQTCpnQGA4aQdHZ1Mv+yblCRr5qXvIMtfdtRXboB2SeVO4xaw36CeRnnf7UUjVwa6lQWIEjGZqp0gJNiI46VBFCFq5cMaPndKujADqw6L59mPhI987nUxdLkQdD1vDNh8GFkl+RhxHOIYXDeH4tZUXBJmG1BZC8h86M2NwTpCchmOz9lPEfWTZN0feEOWC6ba6iq5dDo4/IpWIAx7ZZstfFEd0KZY2Jmwn8EPvcAN7lZIMXC+BrFjkPCY617bg/p0zqcOFhNkPP1ehtz+ZVxDNLeoQRLmCFU2yRmJZfqJ+DrFm1zvlCpbfCmhDZsi39YkrmhORD/yeM6xK+/yoOSh5QpnxGLbca4SJV7uJZPdMLh2aEjRyl1UbqmGHEYkDqcjnANotbqZCJTq8xgMmlsX/LlrhompUqI2DEL8VDNEW5Rp4gnxPe7U5e8+Rqc+HhYil9GwYLeqEL+IU4sV/0KGJb2vgWoZgaN4Afovg52IkAfvD8Nc="
  app: ksiazekm-jaa-api
  on:
    repo: ksiazekm/JAlgoArena-API
