language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: heroku
  api_key:
   secure: "0iN48HZECWwW67tJCk4tx54wRCIQZg5Q1guwQoa8mLujjTaa68ZveXaLYKtCgk3Wr9g9Ot5GTtFiGpkL1ERdASIRHT/Sxv1glDi5SRJUVElCdxDTC9KgtkgDlTdLFY89aEIYcVcPQqcJcdP3YL7ZJex8crMp8JBVfki23HwpuD5pbVu6JxWRhwWWxv6BQkRnckmNXmkitVuWZWdlonLf/pRiAoREAmOh410JBPpZK7mR9HAwyWWq3Xfl99Ku4H6dLCb3/dvXr4zuB4nf6fcAnvj9pKMkl9osM+FtE7jK9cfnbsyFHn1Qq//MxgE/vMpDeHMkOy4cQ+0Rqnh8RpJ69YiG0+hXeziLryAdTdvCC1MoHpP45vLdjNz3dVR0XiO78HdioDb3TJDHzqBUDTCdZhCP2Pm/k3ALCuXU1ok2GE6xStwoiEmqYuriPPt1Mrk01R3R/Ay97oJgcISUEr7s0SXHxgGUNTi9/KW2M4CryJrVaB/SqGroag1s0zP+xkymm3ruAs7ZyzgqJOWeVbowmGEtpuU0VY9Y+psIkGBBnyB3tr+6aMDq7STwk7aDhWb6AbNNYqGLhfe2vgnl0V2eljjstH5AA+1Q+ichDDvO1Dg9TcB4Er6AdrG5P3ZNOIqrjfVdEjc2YH7TE3mmR0EcDrOfbUenGj6Yr2qC6fNfHvk="
  app: mksiazek-jaa-api
  on:
    repo: ksiazekm/JAlgoArena-API
